Avoid `package hyphen-japanese not present` error
```console
(snip)
Rendering PDF
running lualatex - 1

  This is LuaHBTeX, Version 1.22.0 (TeX Live 2025)
   restricted system commands enabled.

updating tlmgr

updating existing packages

finding package for ltjsarticle.cls

> 1 package to install
> installing luatexja (1 of 1)

  This is LuaHBTeX, Version 1.22.0 (TeX Live 2025)
   restricted system commands enabled.

  luaotfload | db : Font names database not found, generating new one.
  luaotfload | db : This can take several minutes; please be patient.

Installing missing hyphenation file...

> 1 package to install
> installing hyphen-japanese (1 of 1)

ERROR: [non-error-thrown] tlmgr returned a non zero status code
tlmgr install: package hyphen-japanese not present in repository.
tlmgr: action install returned an error; continuing.
tlmgr: An error has occurred. See above messages. Exiting.

Stack trace:
tlmgr install: package hyphen-japanese not present in repository.
tlmgr: action install returned an error; continuing.
tlmgr: An error has occurred. See above messages. Exiting.

    at Command.handleError (file:///opt/quarto/bin/quarto.js:8278:126)
    at Command.parseCommand (file:///opt/quarto/bin/quarto.js:8003:18)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async quarto (file:///opt/quarto/bin/quarto.js:126631:9)
    at async file:///opt/quarto/bin/quarto.js:126658:9
    at async mainRunner (file:///opt/quarto/bin/quarto.js:126523:9)
    at async file:///opt/quarto/bin/quarto.js:126649:5

rake aborted!
Command failed with status (1): [bundle exec quarto render doc/notebook/preprocess_knock_Ruby-RedAmber.ipynb --execute-daemon-restart --execute]

/workspaces/100knocks-preprocess-ruby/Rakefile:32:in 'block (2 levels) in <top (required)>'
/workspaces/100knocks-preprocess-ruby/Rakefile:30:in 'block in <top (required)>'
Tasks: TOP => test
(See full trace by running task with --trace)
```