[System] Register iruby as ruby in Jupyter kernel
The following error happened because Jupyter kernel
expects the ruby although it is registered as ruby3.

So, we register iruby as ruby because it will be
flexible in ther futuer when we use the ruby version
over 3.

```console
$ rake convert
mkdir -p doc/notebook
quarto convert doc/qmd/preprocess_knock_Ruby-RedAmber.qmd -o doc/notebook/preprocess_knock_Ruby-RedAmber.ipynb
ERROR: Jupyter kernel 'ruby' not found. Known kernels: python3, ruby3. Run 'quarto check jupyter' with your python environment activated to check python version used.

Stack trace:
    at jupyterKernelspecFromMarkdown (file:///opt/quarto/bin/quarto.js:32283:35)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async quartoMdToJupyter (file:///opt/quarto/bin/quarto.js:32111:36)
    at async markdownToJupyterNotebook (file:///opt/quarto/bin/quarto.js:108107:22)
    at async Command.actionHandler (file:///opt/quarto/bin/quarto.js:108245:105)
    at async Command.execute (file:///opt/quarto/bin/quarto.js:8111:13)
    at async Command.parseCommand (file:///opt/quarto/bin/quarto.js:8001:20)
    at async quarto (file:///opt/quarto/bin/quarto.js:126631:9)
    at async file:///opt/quarto/bin/quarto.js:126658:9
    at async mainRunner (file:///opt/quarto/bin/quarto.js:126523:9)
rake aborted!
Command failed with status (1): [quarto convert doc/qmd/preprocess_knock_Ruby-RedAmber.qmd -o doc/notebook/preprocess_knock_Ruby-RedAmber.ipynb]
/workspaces/100knocks-preprocess-ruby/Rakefile:20:in `block (2 levels) in <top (required)>'
Tasks: TOP => convert => doc/notebook/preprocess_knock_Ruby-RedAmber.ipynb
(See full trace by running task with --trace)
```