Alter kernel name ruby3 instead of ruby
Because `rake jupyter` is failed as following error:

```console
$ rake jupyter
quarto convert doc/qmd/preprocess_knock_Ruby-RedAmber.qmd -o
doc/notebook/preprocess_knock_Ruby-RedAmber.ipynb
ERROR: Jupyter kernel 'ruby' not found. Known kernels: python3, ruby3.
Run 'quarto check jupyter' with your python environment activated to
check python version used.
```